/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dartapplication;

import java.awt.ComponentOrientation;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Yogi
 */
public class GlobalFrame extends javax.swing.JFrame {

    /**
     * Creates new form GlobalFrame
     */
    public GlobalFrame() {
        initComponents();
       // s = new SingleKO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        PlikMENU = new javax.swing.JMenu();
        NewMenu = new javax.swing.JMenu();
        NewPlayerMenu = new javax.swing.JMenuItem();
        NewTournamentMenu = new javax.swing.JMenuItem();
        NewRaportMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ZamknijMENU = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Let's Play Dart!");

        PlikMENU.setText("Plik");

        NewMenu.setText("Nowy");

        NewPlayerMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        NewPlayerMenu.setText("Nowy Gracz");
        NewPlayerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPlayerMenuActionPerformed(evt);
            }
        });
        NewMenu.add(NewPlayerMenu);

        NewTournamentMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        NewTournamentMenu.setText("Nowy Turniej");
        NewMenu.add(NewTournamentMenu);

        NewRaportMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        NewRaportMenu.setText("Nowy Raport");
        NewMenu.add(NewRaportMenu);

        PlikMENU.add(NewMenu);
        PlikMENU.add(jSeparator1);

        ZamknijMENU.setText("Zamknij");
        ZamknijMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijMENUActionPerformed(evt);
            }
        });
        PlikMENU.add(ZamknijMENU);

        jMenuBar1.add(PlikMENU);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZamknijMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijMENUActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ZamknijMENUActionPerformed

    private void NewPlayerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPlayerMenuActionPerformed
        // TODO add your handling code here:
        new AddPlayerFrame();
    }//GEN-LAST:event_NewPlayerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobalFrame().setVisible(true);
            }
        });
    }

    private GameSystem s;
    public static List<Player> globalplayerlist = new ArrayList<Player>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu NewMenu;
    private javax.swing.JMenuItem NewPlayerMenu;
    private javax.swing.JMenuItem NewRaportMenu;
    private javax.swing.JMenuItem NewTournamentMenu;
    private javax.swing.JMenu PlikMENU;
    private javax.swing.JMenuItem ZamknijMENU;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
